version: "3.8"

name: infra

services:
  caddy:
    build: ../../containers/caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /data/sync/infra/caddy:/data/caddy
    restart: unless-stopped

  discord_music_bot:
    build: ../../containers/discord_music_bot
    env_file: ../../secrets.env
    restart: unless-stopped

  syncthing:
    image: syncthing/syncthing:1.27.3
    hostname: box-10
    environment:
      - PUID=0
      - PGID=0
    ports:
      - 22000:22000/tcp
      - 22000:22000/udp
    volumes:
      - /data/syncthing:/var/syncthing
      - /data/sync:/data/sync
    restart: unless-stopped
